name: CI Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: echo "SITE_URL=http://ec2-54-169-205-92.ap-southeast-1.compute.amazonaws.com:3000" >> .env

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t pat0112/spendy .
      - name: Push to Dockerhub
        run: docker push pat0112/spendy:latest

  provision-ec2:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: ap-southeast-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        id: apply
        env:
          # TF_VAR_ec2_name: '${{ github.event.inputs.ec2-name }}'
          TF_VAR_dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          terraform plan 
          terraform apply -auto-approve

  # deploy:
  #   needs: [build]
  #   runs-on: self-hosted

  #   steps:
  #     - name: Delete Old docker container
  #       run: sudo docker rm -f spendy-container
  #     - name: Pull Docker image
  #       run: sudo docker pull pat0112/spendy:latest
  #     - name: Run Docker Container
  #       run: sudo docker run -d -p 3000:3000 --name spendy-container pat0112/spendy
