name: CI Pipeline

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: echo "SITE_URL=http://ec2-54-169-205-92.ap-southeast-1.compute.amazonaws.com:3000" >> .env

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t pat0112/spendy .
      - name: Push to Dockerhub
        run: docker push pat0112/spendy:latest

  deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Delete Old docker container
        run: sudo docker rm -f spendy-container
      - name: Pull Docker image
        run: sudo docker pull pat0112/spendy:latest
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name spendy-container pat0112/spendy
