# Contoh untuk GitHub Actions
name: DAST

on: [push]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start application
        run: |
          npm install
          npm start &
          sleep 15
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network="host" owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000 -r zap_report.html
      - name: Upload ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
