name: CI/CD Pipeline for testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t pat0112/spendy .
      - name: Push to Dockerhub
        run: docker push pat0112/spendy:latest

  launch:
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Delete Old docker container
        run: sudo docker rm -f spendy-container
      - name: Pull Docker image
        run: sudo docker pull pat0112/spendy:latest
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name spendy-container pat0112/spendy

  soos:
    needs: [build, launch]
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@a7f2cb2dfd143cb3224712d902ca0a1da0198ea9
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "DAST-GitHub-Action"
          scan_mode: "baseline"
          target_url: "http://ec2-18-136-106-83.ap-southeast-1.compute.amazonaws.com:3000"
          output_format: "sarif"
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
